# Generated by Django 3.2.12 on 2022-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_foreign_students_time_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreign_students',
            options={'ordering': ['-author'], 'verbose_name': 'Шетел студенттер', 'verbose_name_plural': 'Шетел студенттер'},
        ),
        migrations.AlterField(
            model_name='article',
            name='score',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=2, verbose_name='Ғылыми жұмыстың бағасы'),
        ),
        migrations.AlterField(
            model_name='foreign_students',
            name='students',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=2, verbose_name='Шетел студенттер саны'),
        ),
    ]
